import ManageGeneratedTimetable from "@/core/components/timetable/desktop/auto/generate/ManageGeneratedTimetable";
import styles from "./page.module.css";

export default function AutoGenerateDesktop() {
    // Render
    return (
        <div className={styles.page}>
            <ManageGeneratedTimetable />
        </div>
    );
}